name: New Citizen
favicon: null
layout_spectrum: 0.6603336380794644
typography_spectrum: 0.31566092511639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.21316434512846172
  lightness: 0.9784136875532568
  saturation: 0.5236731613986194
  rhythmicContrast: 0.2286027108784765
purpose: []
